name: Plan & Apply Infra

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  terraform-infra:
    name: Terraform Infra
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/infra

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      # Create input variables from Environment Secret
      # NOTE: Avoid terraform.tfvars
      - name: Setup Terraform variables
        run: cp terraform.tfvars.example terraform.auto.tfvars

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      # Adds a comment to the pull request with results of the format, init and plan
      - name: Update Pull Request
        id: add-comment
        uses: actions/github-script@v4
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style: ${{ steps.fmt.outcome }}
            #### Terraform Initialization: ⚙️ ${{ steps.init.outcome }}
            #### Terraform Plan: ${{ steps.plan.outcome }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # Print result of the github-script
      - name: Get result
        if: github.event_name == 'pull_request'
        run: echo "${{steps.add-comment.outputs.result}}"

      # Exit if terraform plan failed
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # Apply the plan if merge to branch master
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

  deploy-k8s-secrets:
    name: K8s Secrets
    needs: terraform-infra
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/app

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true


      # Get the GKE credentials so we can deploy to the cluster
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: dev-gke-001-cluster
          location: asia-northeast1-b
          use_auth_provider: true

      # Generates Secrets
      - name: Execute script
        run: ./secrets.sh
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}

  terraform-app:
    name: Terraform App
    needs:
      - terraform-infra
      - deploy-k8s-secrets
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/app

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true


      # Get the GKE credentials so we can deploy to the cluster
      # NOTE: There is a Github Action https://github.com/google-github-actions/get-gke-credentials but it will not create ~/.kube/config
      # NOTE: ~/.kube/config will be created
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials dev-gke-001-cluster --zone asia-northeast1-b --project ${{ secrets.GCP_PROJECT }}

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      # Create input variables from Environment Secret
      # NOTE: Avoid terraform.tfvars
      - name: Setup Terraform variables
        run: cp terraform.tfvars.example terraform.auto.tfvars

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      # Apply the plan if merge to branch master
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Deployment Confirm
      - name: Deploy
        run: kubectl get services -o wide
