name: Deploy K8S Secrets

on: workflow_dispatch

jobs:
  deploy-secrets:
    name: K8s Secrets
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src/app

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true


      # Get the GKE credentials so we can deploy to the cluster
      # NOTE: There is a Github Action https://github.com/google-github-actions/get-gke-credentials but it will not create ~/.kube/config
      # NOTE: ~/.kube/config will be created
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials dev-gke-001-cluster --zone asia-northeast1-b --project ${{ secrets.GCP_PROJECT }}

      # Generates Secrets
      - name: Execute script
        run: ./secrets.sh

